### ISSUE TITLE
People actually use this as malware, for example in plugins for minecraft servers.

### ISSUE THREAD

**Issue by Janmm14** [D4stiny/jWARE#2]

**Comment by D4stiny** [comment]
Hi, could you provide more information? I understand the basic structure of a minecraft plugin, and someone would need to modify my project in order to be one. Also, most hosts don't allow plugins to write to files outside of their server folder, if they do, that is more of a host problem.

**Comment by D4stiny** [comment]
Hi, I've done some preliminary research into this issue you brought up and found this [forum thread](https://www.spigotmc.org/threads/ransomware-on-spigotmc.309614/). I wouldn't be surprised if the perpetrator was using my project as a source, but it is not like I implemented a kill switch. The source at it's current state is pretty hard to be used maliciously. 

Not sure what you're hoping to achieve with this issue, a lot of open source software can be used maliciously, mine is no different. If you have any comments, please post them within 24 hours or I will close this issue. Thanks!

**Comment by Janmm14** [comment]
Just wanted to show you that such stuff is used.

**Comment by D4stiny** [comment]
Alright, I definitely am not happy that it is being used maliciously, but like I said, there's nothing I can really do. Thank you for reporting though.
